### ISSUE TITLE
Improve documentation for logging

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/gravitee-gateway#62]
Add some doc to explain how to add logback configuration.

**Comment by brasseld** [comment]
@aelamrani: What do you need exactly ? A simple reference to SLF4J documentation is not sufficient ?

**Comment by aelamrani** [comment]
I do not need, but the future users does :)
Not about how to write it, but where to put it...

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/ichiou#6
