### ISSUE TITLE
gateway is inconsistent with last '/' on context path or endpoint

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/gravitee-gateway#86]
I think Gravitee.io must have the same behavior with / or not at the end of endpoint and context path.
Here is how gravitee.io handles the last /

context path | endpoint | http://localhost/swapi/ | http://localhost/swapi | http://localhost/swapi/people
-----------------|-------------|-------------------------------|------------------------------|--------------------------------------
/swapi | http://swapi.co/api | 200                           | 200                          | 200
/swapi | http://swapi.co/api/ | 404 (from swapi)     | 200                          | 404 (from swapi)
/swapi/ | http://swapi.co/api | 404 (from gateway) | 404 (from gateway) | 404 (from gateway)
/swapi/ | http://swapi.co/api/ | 404 (from gateway) | 404 (from gateway) | 404 (from gateway)

What do you think ?

**Comment by brasseld** [comment]
This is really interesting !
Will have a look soon.

**Comment by brasseld** [comment]
@NicolasGeraud Do you think we have to accept context-path with a final '/' ?
